name: Headless Testing

on:
  push:
    branches: [ 'main', 'mocha-*', 'chai-*', 'test-*', 'behave-*', 'selenium-*' ]
  workflow_dispatch:

jobs:
  headless_testing:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install Chai & Mocha
        run: |
          echo "$ npm install chai & mocha "
          npm install chai mocha
          echo "$ npm mocha --version"
          npm mocha --version
      - name: Start HTTP Server
        run: |
          echo "$ npx http-server "
          npx http-server &
      - name: Test headless.mjs
        run: |
          echo "$ npm run test"
          npm run test
  behavioral_headless_testing:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install Selenium & Behave
        run: |
          echo "$ pip install Selenium"
          pip install Selenium
          echo "$ pip install behave"
          pip install behave
      - name: Start HTTP Server
        run: |
          echo "$ npx http-server "
          npx http-server &
      - name: Test walking.py
        run: |
          echo "$ behave"
          behave